---
- name: 사전 점검, 설치 및 사후 점검
  hosts: all
  become: yes
  tasks:
    # 사전 점검 - 우분투 버전 확인
    - name: 우분투 버전 확인
      block:
        # 우분투 버전 확인
        - name: 우분투 버전 확인
          command: lsb_release -rs
          register: ubuntu_version

        # 우분투 버전이 22.x가 아닌 경우 실패
        - name: 우분투 버전이 22.x가 아닌 경우 실패
          fail:
            msg: "이 플레이북은 우분투 22.x를 대상으로 합니다. 현재 버전은 {{ ubuntu_version.stdout }} 입니다."
          when: ubuntu_version.stdout.find("22.") != 0
      rescue:
        - name: 사전 점검에서 실패한 경우 플레이북 종료
          meta: end_play
          
    # 설치 - Nginx 설치
    - name: Nginx 설치
      block:
        # apt 패키지 캐시 업데이트
        - name: apt 패키지 캐시 업데이트
          apt:
            update_cache: yes

        # Nginx 설치
        - name: Nginx 설치
          apt:
            name: nginx
            state: present
          notify:
            - nginx 시작

      rescue:
        - name: 설치에서 실패한 경우 플레이북 종료
          meta: end_play

  handlers:
    # Nginx 시작
    - name: nginx 시작
      service:
        name: nginx
        state: started

- name: 사후 점검 - Nginx 설치 확인
  hosts: your_server
  become: yes
  tasks:
    # Nginx 설치 확인
    - name: Nginx 설치 확인
      block:
        # Nginx가 설치되었는지 확인
        - name: Nginx 설치 확인
          command: nginx -v
          register: nginx_version
          ignore_errors: yes

        # Nginx가 설치되지 않은 경우 실패
        - name: Nginx가 설치되지 않은 경우 실패
          fail:
            msg: "Nginx가 설치되지 않았습니다."
          when: nginx_version.rc != 0
      rescue:
        - name: 사후 점검에서 실패한 경우 플레이북 종료
          meta: end_play
