---
- name: 사후 점검 - Nginx 설치 확인
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Nginx 설치 확인
      command: nginx -v
      register: nginx_version
      ignore_errors: yes

    - name: Nginx가 설치되지 않은 경우 실패
      fail:
        msg: "Nginx가 설치되지 않았습니다."
      when: nginx_version.rc != 0
