---
- name: 설치 - Nginx 설치
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Nginx 설치
      apt:
        name: nginx
        state: present
      notify:
        - nginx 시작

  handlers:
    - name: nginx 시작
      service:
        name: nginx
        state: started
