---
- name: 설치 - Nginx 설치
  hosts: all
  become: yes
  tasks:
    - name: Nginx 설치
      block:
        - name: apt 패키지 캐시 업데이트
          apt:
            update_cache: yes

        - name: Nginx 설치
          apt:
            name: nginx
            state: present
          notify:
            - nginx 시작
      rescue:
        - name: 설치에서 실패한 경우 플레이북 종료
          meta: end_play

  handlers:
    - name: nginx 시작
      service:
        name: nginx
        state: started
