---
- name: 사전 점검 - 우분투 버전 확인
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: 우분투 버전 확인
      command: lsb_release -rs
      register: ubuntu_version

    - name: 우분투 버전이 22.x가 아닌 경우 실패
      fail:
        msg: "이 플레이북은 우분투 22.x를 대상으로 합니다. 현재 버전은 {{ ubuntu_version.stdout }} 입니다."
      when: ubuntu_version.stdout.find("22.") == -1
