---
- name: 사후 점검 - Nginx 설치 확인
  hosts: all
  become: yes
  tasks:
    - name: Nginx 설치 확인
      block:
        - name: Nginx 설치 확인
          command: nginx -v
          register: nginx_version
          ignore_errors: yes

        - name: Nginx가 설치되지 않은 경우 실패
          fail:
            msg: "Nginx가 설치되지 않았습니다."
          when: nginx_version.rc != 0
      rescue:
        - name: 사후 점검에서 실패한 경우 플레이북 종료
          meta: end_play
