- name: Check CPU Usage on Ubuntu 22
  hosts: all
  gather_facts: no
  tasks:
    - name: Get CPU usage
      shell: "top -bn1 | grep 'Cpu(s)' | sed 's/.*, *\\([0-9.]*\\)%* id.*/\\1/'"
      register: cpu_usage_output

    - name: Print CPU usage
      debug:
        msg: "{{cpu_usage_output.stdout}}"
